### PR TITLE
Add additional contract type to ltm_1.6

### PR DESCRIPTION
**Pull request by qduk**
Provides the same feature as #239 but with respect to the ltm_1.6 branch. The table in the docs was using config items from Golden Config so I changed the table to match the plugin.

### CODE REVIEW

**Comment by bradh11** [comment]
@qduk - Thank for the updates and resubmitting this PR.  Looks much better now against the ltm1.6 branch.

**Comment by progala** [comment]
@qduk Having a second look at this I think it could be worthwile to load additional contract types from environment, see my suggestion. Could you please add tests for `add_custom_contract_types`?

**Review by progala — CHANGES_REQUESTED** [review]

**Comment by qduk** [comment]
@progala Test have been added and your suggestions committed! Let me know if those test do not suffice.

**Comment by qduk** [comment]
@progala Do we want to go ahead and close one due to the discussion you had with John? Sounds like we will need to rethink the approach on this so it propagates everywhere a new contract type would be needed.

**Comment by progala** [comment]
Closed as agreed. New approach is needed.

**Pull request closed without merging**
