### PR TITLE
hardware API andpoint implementation is incompatible with nautobot-ansible plugin module.

### PR DESCRIPTION
**Pull request by pszulczewski**
See the issue in nautobot-ansible for more information.
https://github.com/nautobot/nautobot-ansible/issues/306
If this PR is accepted it would need a new major release.

### CODE REVIEW

**Comment by progala** [comment]
Thanks @pszulczewski . With it being a breaking change we'll target this to be merged into the next3.0 release.

**Comment by progala** [comment]
@pszulczewski Can you give an example of an API call that works now and will stop working once this is merged? We'll need to properly document it so that users are aware of changes they need to make.

**Comment by pszulczewski** [comment]
@progala field names in filtered API calls will change like this:

current filtered API call:
`'https://<host>/api/plugins/nautobot-device-lifecycle-mgmt/hardware/?device_type=Catalyst+6509-E'`
will change to:
`'https://<host>/api/plugins/nautobot-device-lifecycle-mgmt/hardware/?device_type_model=Catalyst+6509-E'`

`device_type` --> `device_type_model`

current filtered API call:
`'https://<host>/api/plugins/nautobot-device-lifecycle-mgmt/hardware/?device_type_id=4bf23e23-4eb1-4fae-961c-edd6f8cbaaf1'`
will change to:
`'https://<host>/api/plugins/nautobot-device-lifecycle-mgmt/hardware/?device_type=4bf23e23-4eb1-4fae-961c-edd6f8cbaaf1'`

`device_type_id` --> `device_type`

**Comment by progala** [comment]
Thanks! That makes sense to me. Could you just add a change fragment and I'll get it merged.

**Pull request merged**
